[project]
name = "second-brain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.0",
    "google-genai>=1.63.0",
    "pydantic-ai>=1.59.0",
    "sentence-transformers>=5.2.2",
]
